// Code generated by "stringer -type ObjectType"; DO NOT EDIT.

package cfb

import "strconv"

const (
	_ObjectType_name_0 = "UnknownObjectStorageObjectStreamObject"
	_ObjectType_name_1 = "RootStorageObject"
)

var (
	_ObjectType_index_0 = [...]uint8{0, 13, 26, 38}
)

func (i ObjectType) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _ObjectType_name_0[_ObjectType_index_0[i]:_ObjectType_index_0[i+1]]
	case i == 5:
		return _ObjectType_name_1
	default:
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
